name: Update data.json

on:
  repository_dispatch:
    types: [sheet-updated]   # ← 受け皿イベント名（任意名）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Build data.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          RANGE: "GoogleMAPプロット用!A:E"   # ← タブ名に合わせて変更
        run: python build.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --cached --quiet || (git commit -m "Update data.json" && git push)
